Realizzazione classe Business e Test
lineCode-swe/server pull request #1
Opened 2021-05-30 15:13 UTC by ValtonTahiraj

2021-05-30 20:43 UTC, achimett requested changes
Commentato dove sono richiesti cambiamenti. In particolar modo per quanto riguarda il comportamento dei Signal, consiglio di guardare i diagrammi di sequenza.

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/UserServiceImpl.java
> +public class UserServiceImpl implements  UserService{
Nessun metodo emette il signal, ma le UI vanno avvisate dei cambiamenti

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/UserServiceImpl.java
> +    }
Numero di parentesi errato. Le parentesi chiuse vanno sempre a capo per essere sicuri di non averne messe in più.
```java
if (cond) {
    istruzione;
} else {
    istruzione;
}

2021-05-30 20:43 UTC, achimett commented on src/main/test/java/org/linecode/server/business/UserServiceImplTest.java
> +
Cambiare da formato JUnit3 a JUnit4 senza estendere il TestCase e con il `@Before`
```suggestion
public class UserServiceImplTest {

    private UserServiceImpl test;
    
     @Before
     public void setUp() {
         test = new UserServiceImpl(Mockito.mock(UserRepository.class), Mockito.mock(Signal1.class));
     }
```

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/UnitServiceImpl.java
> +    private final Signal2<String, Integer> speedSignal;
Segnali mai emessi, ma la UI va avvisata di tali cambi

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/UnitServiceImpl.java
> +    private final Signal1<String> poiSignal;
Segnale mai emesso, ma la UI va avvisata di tale cambio

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/UnitServiceImpl.java
> +            units.add(new Unit(id,repo.getName(id),repo.getBase(id)));
NullPointerException

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/MapServiceImpl.java
> +    private final Signal1<List<Position>> obstaclesSignal;
Questi segnali non vengono mai inviati, ma la UI deve conoscere questi cambiamenti

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/MapServiceImpl.java
> +    private final MapRepository mapRepo;
`mapRepo` non viene mai richiamato ma il db deve venire aggiornato con le nuove informazioni e quelle vecchie devono essere richiamate dal db alla partenza del software perché su Grid non sono persistenti

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/MapServiceImpl.java
> +    private final UnitRepository unitRepository;
L'IDE segnala che non `unitRepository` viene mai richiamato. Se non serve può essere eliminato.

2021-05-30 20:43 UTC, achimett commented on src/main/test/java/org/linecode/server/business/MapServiceImplTest.java
> +    MapServiceImpl test = new MapServiceImpl(map,unitRepo,obsRepo,mapRepo,unitRepository,mapSignal,obstaclesSignal);
Stesse raccomandazioni fatte su `UnitServiceImplTest`

2021-05-30 20:43 UTC, achimett commented on src/main/test/java/org/linecode/server/business/MapServiceImplTest.java
> +    Signal1<List<Position>> obstaclesSignal= Mockito.mock(Signal1.class);
L'IDE lamenta che i mock non hanno i generics. Operare un'opportuna conversione per poter fare l'assegnazione.

2021-05-30 20:43 UTC, achimett commented on pom.xml
> +
Cambiare come da suggerimento anche la versione di JUnit
```suggestion
     <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>3.5.15</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-inline</artifactId>
      <version>3.5.15</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
```

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/Position.java
> +    }
Per rispondere al commento di riga 23: no, non va bene e non è riportato in architettura

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/Grid.java
> +    //public Cell getCell(int x, int y) { return g[x][y]; }
Rimuovere commento

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/Grid.java
> +        return toReturn; //TODO: Possibile nullpointer
TODO

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/MapServiceImpl.java
> +        //TODO Estrapolare dal POC UnitEndpoint l'algoritmo di pathfinding
TODO

2021-05-30 20:43 UTC, achimett commented on src/main/test/java/org/linecode/server/business/MapServiceImplTest.java
> +    // TODO: Checkare questo test
TODO

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/persistence/Cell.java
> +    private final Direction direction ; // "UP,DOWN,LEFT,RIGHT" TODO: Chiedere a Achimetto se è final
Sì, è final. Togli pure il commento

2021-05-30 20:43 UTC, achimett commented on src/main/java/org/linecode/server/business/UnitStatus.java
> +    }
In questo modo viene "aggirato" l'utilizzo dell'enum salvando un intero che poi viene richiamato tale e quale. L'enum lega naturalmente dei numeri naturali ad ogni sua costante ed è possibile lavorare tramite essi. Fonte breve ma esaustiva: https://www.javatpoint.com/enum-in-java. Da correggere anche sul diagramma.

2021-05-30 20:43 UTC, achimett commented on src/main/test/java/org/linecode/server/business/GridTest.java
> +}
🤔

2021-05-31 13:28 UTC, ValtonTahiraj commented on src/main/java/org/linecode/server/Position.java
> +    }
Era rimasto dal poc credo

2021-05-31 13:29 UTC, ValtonTahiraj commented on src/main/java/org/linecode/server/Position.java
> +    }
Okay nvm, è una cosa che dovrebbe aver aggiunto Paolo, bisogna parlarne con lui

2021-06-02 19:08 UTC, achimett requested changes

2021-06-02 19:08 UTC, achimett commented on src/main/java/org/linecode/server/persistence/Cell.java
> +    private boolean poi = false;
`poi` dovrebbe essere _final_ e inserito nel costruttore

2021-06-02 19:08 UTC, achimett commented on src/main/test/java/org/linecode/server/business/MapServiceImplTest.java
> +    // TODO: Checkare questo test
Se hai fatto il TODO puoi togliere il commento 🙃

2021-06-02 19:08 UTC, achimett commented on src/main/java/org/linecode/server/business/MapServiceImpl.java
> +                    lista.add(new Cell(new Position(x, y), false, false, Direction.ALL).createPoi(true));
Correggere con la cella che ha `poi` come campo _final_

2021-06-02 19:08 UTC, achimett commented on src/main/java/org/linecode/server/business/UnitServiceImpl.java
> +        positionSignal.emit(id,base);
Non emette `positionSignal` che va emesso quando l'unità cambia posizione. Crea un nuovo `Signal1<List<Unit>> unitSignal` e emetti l'intera lista di unità. Lo stesso segnale deve essere emesso anche da `delUnit()` per avvisare tutte le UI della cancellazione dell'unità

2021-06-02 21:21 UTC, merged